// 10_AprendiendoVue/src/components/Formulario.vue
<template>
<div class="general">
     <Slider texto="Formulario" />
        <div class="center">
            <section id="content">
                <h2 class="subheader">Formulario</h2>
              <form class="mid-form"  @submit.prevent="mostrarUsuario()" >

                <div class="form-group">
                    <label for="nombre">Nombre: </label>
                    <input type="text" name="nombre" v-model="user.nombre">
                    <div v-if="submited && !$v.user.nombre.required">
                        Este campo es requerido
                    </div>
                    <div v-if="submited && !$v.user.nombre.minLength">
                        Este campo debe tener mas caracteres
                    </div>
                </div>


                <div class="form-group">
                    <label for="apellidos">Apellidos: </label>
                    <input type="text" name="nombre" v-model="user.apellidos">
                     <div v-if="submited && !$v.user.apellidos.required">
                        Este campo es requerido
                    </div>
                     <div v-if="submited && !$v.user.apellidos.minLength">
                        Este campo debe tener mas caracteres
                    </div>
                </div>


                <div class="form-group">
                    <label for="bio">Biografia: </label>
                    <textarea name="bio" v-model="user.bio"></textarea>
                    <div v-if="submited && !$v.user.bio.required">
                        Este campo es requerido
                    </div>
                     <div v-if="submited && !$v.user.bio.minLength">
                        Este campo debe tener mas caracteres
                    </div>
                </div>


                <div class="form-group raddiobuttons">
                    <input type="radio" name="genero" id="genero" value="hombre" checked v-model="user.genero" />Hombre
                    <input type="radio" name="genero" id="genero" value="mujer" v-model="user.genero"  />Mujer
                    <input type="radio" name="genero" id="genero" value="otros" v-model="user.genero"  />Otros
                </div>

                <div class="clearfix"></div>

                <input type="submit" value="Enviar" class="btn btn-success">

                <div class="datos" v-if="user.nombre && user.apellidos">
                    <h3>{{user.nombre + ' ' + user.apellidos}}</h3>
                 </div>   

            </form>
            </section>
             <Sidebar />
          <div class="clearfix"></div>

       </div>  
</div>   
</template>

<script>
import {required, minLength} from 'vuelidate/lib/validators'
import Slider from './Slider.vue'
import Sidebar from './Sidebar.vue'
export default {
    name: 'Formulario',
    components: {
        Slider,
        Sidebar
    },
    validations: {
        user: {
         nombre: {
            required,
            minLength: minLength(2),
        },
        apellidos: {
            required,
            minLenght: minLength(2),
        },
        bio: {
            required,
            minLenght: minLength(10)
        }
        }
      
    },
    data(){
        return {
            submited: false,
            user:{
                nombre: '',
                apellidos: '',
                bio: '',
                genero: ''
            }
        }
    },
    methods:{
        mostrarUsuario(){
            console.log(this.user);
            this.submited = true;
            this.$v.$touch();
            if(this.$v.$invalid){
                return false;
            }

            alert("validacion pasada");
        }
    }
}
</script>

// 07_BlogAngular/src/app/componente/formulario/formulario.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-formulario',
  templateUrl: './formulario.component.html',
  styleUrls: ['./formulario.component.css']
})
export class FormularioComponent implements OnInit {
  public user: any;
  public campo: string;
  constructor() { 

    this.user = {
      nombre: '',
      apellidos: '',
      bio: '',
      genero: ''
    };

  }

  ngOnInit(): void {
  }

  onSubmit() { 
    alert("Formulario enviado!!!");
    console.log(this.user);
  }

  hasDadoClick() { 
    alert("Haz dado click!");
  }

  hasSalido() {
    //alert("Has salido!!");
    alert("has Pulzado el enter");
   }

}

<app-slider [nombre]="'Formulario'" [size]="'small'">

</app-slider>

<div class="center">
    <section id="content">

        <h1 class="subheader">Formulario</h1>
        <!--
        <div id="datos-al-vuelo" *ngIf="user.nombre">
            <h2 class="subheader">Datos al vuelo</h2>
            <ul>
                <li>
                    {{user.nombre}}
                </li>
                <li>
                    {{user.apellidos}}
                </li>
                <li>
                    {{user.bio}}
                </li>
                <li>
                    {{user.genero}}
                </li>
            </ul>
        </div>
        -->
        <form class="mid-form" #userForm="ngForm" (ngSubmit)="onSubmit()">

            <div class="form-group">
                <label for="nombre">Nombre: </label>
                <input type="text" name="nombre" #nombre="ngModel" [(ngModel)]="user.nombre" required pattern="[a-zA-Z]+" />
                <small *ngIf="!nombre.valid && nombre.touched ">
                    El nombre no es válido
                </small>
            </div>


            <div class="form-group">
                <label for="apellidos">Apellidos: </label>
                <input type="text" name="apellidos" #apellidos="ngModel" [(ngModel)]="user.apellidos" required pattern="[a-zA-Z]+" />
                <small *ngIf="!apellidos.valid && apellidos.touched ">
                    El apellido no es válido
                </small>
            </div>


            <div class="form-group">
                <label for="bio">Biografia: </label>
                <textarea name="bio" #bio="ngModel" [(ngModel)]="user.bio" required></textarea>
                <small *ngIf="!apellidos.valid && apellidos.touched ">
                    La biografia no es válido
                </small>

            </div>


            <div class="form-group raddiobuttons">
                <input type="radio" name="genero" value="hombre" #genero="ngModel" [(ngModel)]="user.genero" required/>Hombre
                <input type="radio" name="genero" value="mujer" #genero="ngModel" [(ngModel)]="user.genero" />Mujer
                <input type="radio" name="genero" value="otros" #genero="ngModel" [(ngModel)]="user.genero" />Otros
                <small *ngIf="!genero.valid && genero.touched ">
                    EL genero no es válido
                </small>
            </div>

            <div class="clearfix"></div>

            <input type="submit" value="Enviar" class="btn btn-success" [disabled]="userForm.invalid" />

        </form>

        <h2 class="subheader">Eventos</h2>
        <button (click)="hasDadoClick()">Dale Click!!</button>
        <!--<input type="text" [(ngModel)]="campo" (blur)="hasSalido()"> {{campo}}-->
        <input type="text" [(ngModel)]="campo" (keyup.enter)="hasSalido()"> {{campo}}
    </section>
    <app-sidebar></app-sidebar>
</div>
