// 07_BlogAngular/src/app/componente/pelicula/pelicula.component.ts
import { Component, OnInit, Input, Output, EventEmitter } from '@angular/core';
import { Pelicula } from '../../models/pelicula';


@Component({
  selector: 'app-pelicula',
  templateUrl: './pelicula.component.html',
  styleUrls: ['./pelicula.component.css']
})
export class PeliculaComponent  implements OnInit {
  @Input() pelicula: Pelicula;

  @Output() MarcarFavorita: EventEmitter<any> = new EventEmitter();  
  

  
  constructor(){ }

  ngOnInit() {
    console.log("Componente iniciado");
  }


  seleccionar(event,pelicula) { 
    this.MarcarFavorita.emit({
       pelicula:pelicula
    });
  }

}

<!--Listado articulos-->
<article class="article-item">
    <div class="image-wrap">
        <img src="{{pelicula.image}}" alt="{{pelicula.title}}" title="Paisaje">
    </div>
    <h2 class="subheader"> {{pelicula.title}}</h2>
    <span class="date">
    Hace 5 minutos
    </span>

    <span class="year" [ngClass]="{'year-green': pelicula.year > 2016, 'year-red': pelicula.year < 2016}">
        {{pelicula.year}}
    </span>
    <a href="#">Leer Mas</a>

    <button (click)="seleccionar($event,pelicula)">Seleccionar como favorita</button>

    <div class="clearfix"></div>
</article>
<!--Añadir Articulos via js-->

// 10_AprendiendoVue/src/components/Pelicula.vue
<template>
            <!--Listado articulos-->
                <article class="article-item" >
                    <div class="image-wrap">
                        <img :src="pelicula.image" :alt="pelicula.title" :title="pelicula.title"  />
                    </div>
                    <h2 class="subheader">{{pelicula.title}}</h2>
                    <span class="date" :class="{
                       'year-green': pelicula.year >= 2015,
                        'year-red': pelicula.year < 2015,
                    }">
                    {{pelicula.year}}
                </span>
                    <a href="#">Leer Mas</a>
                    <input type="button" value="Marcar Como Favorita" @click="pasarFavoritaAlPadre(pelicula)" />
                    <div class="clearfix"></div>
                </article>
                <!--Añadir Articulos via js-->
</template>

<script>
export default {
    name: 'Pelicula',
    props: ['pelicula'],
    methods: {
        pasarFavoritaAlPadre(pelicula){
            //console.log(pelicula);
            //alert("boton pulsar");
            this.$emit('favorita',pelicula);
        }
    } 
}
</script>
