// 10_AprendiendoVue/src/components/Article.vue
<template>

<div class="general">
        <div class="center">

            <section id="content">
                <h2 class="subheader">Blog</h2>
                 <div id="articles">

                <!--Listado articulos-->
                <article class="article-item article-detail" v-if="article" >
                    <div class="image-wrap">
                          <img :src="url+'get-image/'+article.image" :alt="article.title" :title="article.title" v-if="article.image" >
                          <img src="https://farm5.staticflickr.com/4363/36346283311_1dec5bb2c2.jpg" :alt="article.title" :title="article.title" v-if="!article.image" >
                    </div>
                    <h1 class="subheader">{{article.title}}</h1>
                    <span class="date">
                    {{article.date | moment("from","now")}}
                    </span>
                    <p>
                        {{article.content}}
                    </p>
                    <div class="clearfix"></div>

                    <router-link class="btn btn-warning" :to="'/editar/'+article._id">Editar</router-link>
                    <a class="btn btn-danger" @click="deleteArticle(article._id)">Eliminar</a>

                </article>
                </div>
            </section>
             <Sidebar />
          <div class="clearfix"></div>

       </div>  
</div>   


</template>

<script>
import Sidebar from './Sidebar.vue'
import axios from 'axios'
import Global from '../Global'
import swal from 'sweetalert'

export default {
    name: 'Article',
    components: {
        Sidebar
    },
    data(){
        return {
            url: Global.url,
            article: null
        }
    },
     mounted(){
      // alert(Global.url);
        var articleId = this.$route.params.id;
        //console.log(articleId);
        this.getArticle(articleId);
        //console.log(this.article);
    },
    methods: {
         getArticle(articleId){
            axios.get(this.url + 'article/'+articleId)
            .then(res => {
                //console.log(res.data.article);
                if(res.data.status == 'success'){
                    //console.log("data"+res);
                    this.article = res.data.article;
                }
                //console.log(this.articles);
            });
        },
        deleteArticle(articleId){
            //alert(articleId);
         swal({
        title: "¿Estas Seguro?",
        text: "Una vez eliminado, el articulo no podras recuperarlo!",
        icon: "warning",
        buttons: [true,true],
        dangerMode: true,
        })
        .then((willDelete) => {
        if (willDelete) {
            axios.delete(this.url + 'article/'+articleId)
            .then(response => {
                console.log(response);
                swal(
                    'Articulo borrado',
                    'El Articulo se ha borrado correctamente',
                    'success'

                );
                this.$router.push('/blog');
            });


      } else { 
        swal(
          'Tranquilo',
          'Tu Articulo no se ha eliminado',
          'info'
        );
      }
    });
            
        }
    }
}
</script>

// 07_BlogAngular/src/app/componente/article/article.component.ts
import { Component, OnInit } from '@angular/core';
import { ArticleService } from '../../services/articles.services';
import { Article } from '../../models/article';
import { Router, ActivatedRoute, Params } from '@angular/router';
import { Global } from '../../services/global';
import SweetAlert from 'sweetalert';

@Component({
  selector: 'app-article',
  templateUrl: './article.component.html',
  styleUrls: ['./article.component.css'],
  providers: [ArticleService]
})
export class ArticleComponent implements OnInit {

  public article: Article;
  public title: string;
  public date: any;
  public image: string;
  public content: string;
  public url: string;
  public _id: string;
  constructor(
    public _articleService: ArticleService,
    private _route: ActivatedRoute,
    private _router: Router
  ) {
    this.url = Global.url;
  }

  ngOnInit(): void {
    this._route.params.subscribe(params => {
      let id = params['id'];
      this._articleService.getArticle(id).subscribe(
        response => {
          if (response.article) {
            this.title = response.article.title;
            this.date = response.article.date;
            this.image = response.article.image;
            this._id = response.article._id;
            console.log(this._id);
            this.content = response.article.content;
          } else {
            this._router.navigate(['/home']);
          }
          //console.log(response);
          
        }, error => {
          this._router.navigate(['/home']);
        }
      );
    });
  }

  delete(id) { 

    swal({
      title: "¿Estas Seguro?",
      text: "Una vez eliminado, el articulo no podras recuperarlo!",
      icon: "warning",
      buttons: [true,true],
      dangerMode: true,
    })
    .then((willDelete) => {
      if (willDelete) {
        this._articleService.delete(id).subscribe(
          response => {
            this._router.navigate(['/blog']);
          }, error => {
            console.log(error);
          }
        );
    
        swal(
          'Articulo Elimado!!',
          'El articulo se ha Eliminado Correctamente',
          'success'
        );


      } else { 
        swal(
          'Tranquilo',
          'Tu Articulo no se ha eliminado',
          'info'
        );
      }
    });


   

  }

}

<div class="center">
    <section id="content">

        <h1 class="subheader">{{title}}</h1>

        <article class="article-item article-detail">
            <div class="image-wrap">
                <img src="{{url + '/get-image/' + image}}" alt="{{title}}" title="Paisaje" *ngIf="image">
                <img src="assets/imagenes/defecto.png" alt="{{title}}" title="Paisaje" *ngIf="!image">
            </div>
            <h1 class="subheader"> {{title}}</h1>
            <span class="date">
                {{date | amLocale: 'es' | amTimeAgo}}
            </span>
            <p>
                {{content}}
            </p>

            <div class="buttons">
                <a [routerLink]="['/blog/editar/', _id]" class="btn btn-warning">Editar</a>
                <a (click)="delete(_id)" class="btn btn-danger">Borrar</a>
            </div>



            <div class="clearfix"></div>
        </article>




    </section>
    <app-sidebar></app-sidebar>
</div>
