// 10_AprendiendoVue/src/components/Sidebar.vue
<template>
      <aside id="sidebar">

            <div id="nav-blog" class="sidebar-item">
                <h3>Puedes hacer esto</h3>
                <router-link to="/crear-articulo" class="btn btn-success">Crear articulo</router-link>

            </div>
            <div id="nav-blog" class="sidebar-item">
                <h3>Buscador</h3>
                <p>Encuentra el articulo que buscas</p>
                <form @submit.prevent="goSearch">
                    <input type="text" name="search" v-model="searchString">
                    <input type="submit" name="subtmit" value="Buscar" class="btn">
                </form>
            </div>
        </aside>

</template>

<script>
export default {
    name: 'Sidebar',
    data(){
        return{
            searchString: null
        }
    },
    methods: {
        goSearch(){
            //console.log(this.searchString);
            this.$router.push('/redirect/'+this.searchString);
        }
    }
}
</script>

// 07_BlogAngular/src/app/componente/sidebar/sidebar.component.ts
import { Component, OnInit } from '@angular/core';
import { Router, ActivatedRoute, Params } from '@angular/router';

@Component({
  selector: 'app-sidebar',
  templateUrl: './sidebar.component.html',
  styleUrls: ['./sidebar.component.css']
})
export class SidebarComponent implements OnInit {
  
  public searchString: string;

  constructor(private _router: Router, private _route : ActivatedRoute) { }

  ngOnInit(): void {
  }

  goSearch() { 
    //alert(this.searchString);
    this._router.navigate(['/buscar', this.searchString]);
  }

}

<aside id="sidebar">

    <div id="nav-blog" class="sidebar-item">
        <h3>Puedes hacer esto</h3>
        <a [routerLink]="['/blog/crear']" class="btn btn-success">Crear articulo</a>
    </div>
    <div id="nav-blog" class="sidebar-item">
        <h3>Buscador</h3>
        <p>Encuentra el articulo que buscas</p>
        <form #searchForm="ngForm" (ngSubmit)="goSearch()">
            <input type="text" name="search" [(ngModel)]="searchString">
            <input type="submit" name="subtmit" value="Buscar" class="btn">
        </form>
    </div>
</aside>

<div class="clearfix"></div>
